www/teacher_planner/src/Entity/Course.php
<?php

namespace App\Entity;

use App\Repository\CourseRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass=CourseRepository::class)
 */
class Course
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $cicle;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Subject", mappedBy="course")
     */
    private $subjects;

    public function __construct()
    {
        $this->subjects = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCicle(): ?string
    {
        return $this->cicle;
    }

    public function setCicle(string $cicle): self
    {
        $this->cicle = $cicle;

        return $this;
    }

    public function getSubjects()
    {
        return $this->subjects;
    }

}

www/teacher_planner/src/Entity/Subject.php
<?php

namespace App\Entity;

use App\Repository\SubjectRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=SubjectRepository::class)
 */
class Subject
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotBlank()
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank()
     * @Assert\Positive
     */
    private $hours_week;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Course", inversedBy="subjects")
     * @ORM\JoinColumn(nullable=false)
     */
    private $course;

    /**
     * @ORM\OneToMany(targetEntity=Schedule::class, mappedBy="subject")
     */
    private $schedules;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="subjects")
     */
    private $users;

    public function __construct()
    {
        $this->schedules = new ArrayCollection();
        $this->users = new ArrayCollection();
    }

    /**
     * @return mixed
     */

    public function getCourse()
    {
        return $this->course;
    }

    /**
     * @param mixed $course
     */
    public function setCourse($course): void
    {
        $this->course = $course;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
    
    public function getHoursWeek(): ?int
    {
        return $this->hours_week;
    }

    public function setHoursWeek(int $hours_week): self
    {
        $this->hours_week = $hours_week;

        return $this;
    }

    /**
     * @return Collection|Schedule[]
     */
    public function getSchedules(): Collection
    {
        return $this->schedules;
    }

    public function addSchedule(Schedule $schedule): self
    {
        if (!$this->schedules->contains($schedule)) {
            $this->schedules[] = $schedule;
            $schedule->setSubject($this);
        }

        return $this;
    }

    public function removeSchedule(Schedule $schedule): self
    {
        if ($this->schedules->removeElement($schedule)) {
            // set the owning side to null (unless already changed)
            if ($schedule->getSubject() === $this) {
                $schedule->setSubject(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addSubject($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            $user->removeSubject($this);
        }

        return $this;
    }
}

www/teacher_planner/src/Form/CourseType.php
<?php

namespace App\Form;

use App\Entity\Course;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class CourseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('cicle', ChoiceType::class, array(
                'choices' => array(
                    'Primària' => 'Primaria',
                    'Secundària' => 'Secundaria'
                ),
                'required'    => true,
                'placeholder' => 'Selecciona el cicle',
                'empty_data'  => null
            ))
            ->add('submit', SubmitType::class)
        ;
    }


    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Course::class,
        ]);
    }
}

www/teacher_planner/src/Controller/CourseController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Subject;
use App\Entity\Schedule;
use App\Entity\Course;
use App\Form\CourseType;
use App\Repository\CourseRepository;
use App\Repository\SubjectRepository;
use App\Repository\ScheduleRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Doctrine\ORM\EntityManagerInterface;

/**
 * @Route("/courses")
 */

class CourseController extends AbstractController
{
    public function __construct(CourseRepository $courseRepository, EntityManagerInterface $entityManager)
    {
        $this->courseRepository = $courseRepository;
        $this->entityManager = $entityManager;
    }


    /**
     * @Route("/add", name="app_addCourse")
     * Mètode per afegir un curs i grabar-lo a la BBDD.
     * @param request $request informació del formulari per tal d'afegir el curs.
     */
    public function addCourse(Request $request)
    {
        $course = new course();
        $form = $this->createForm(courseType::class, $course);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $course->setName($form['name']->getData());
            $course->setCicle($form['cicle']->getData());

            $entityManager = $this->getDoctrine()->getManager();

            // tell Doctrine you want to (eventually) save the course
            $entityManager->persist($course);

            // actually executes the action in the ddbb (in this case insert course)
            $entityManager->flush();

            return $this->redirectToRoute('app_getCourses');
        }

        return $this->render('course/add.html.twig', [
            'controller_name' => 'courseController',
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/", name="app_getCourses")
     * Mètode per llistar tots els cursos donats d'alta.
     */
    public function showCourses()
    {
        $entityManager = $this->getDoctrine()->getManager();
        $allCourses = $entityManager->getRepository(Course::class)->findAll();
        return $this->render('course/allCourses.html.twig', [
            'allCourses' => $allCourses,
        ]);
    }

    /**
     * @Route("/delete/{id}", name="app_deleteCourses")
     * Mètode per borrar el curs passat per paràmetre
     * @param Integer $id id del curs a borrar.
     */
// @Jaume: Trobo excepcions al intentar executar aquest mètode, retiro el botó fins revisar
    public function deleteCourse($id)
    {
        $entityManager = $this->getDoctrine()->getManager();

        $course = $entityManager->getRepository(Course::class)->find($id);

        if (!$course) {
            throw $this->createNotFoundException(
                'No existeix cap curs amb id ' . $id
            );
        }
        $entityManager->remove($course);
        $entityManager->flush();

        return $this->redirectToRoute('app_getCourses');
    }

    /**
     * @Route("/edit/{id}", name="app_editCourses")
     * Mètode per editar el curs per paràmetre
     * @param Integer $id id del curs a editar.
     */

    public function updateCourse(Course $course, Request $request): Response
    {
        $form = $this->createForm(CourseType::class, $course);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->flush();

            return $this->redirectToRoute('app_getCourses');
        }

        return $this->render('course/add.html.twig', ['form' => $form->createView()]);
    }

    /**
     * @Route("/{id}", name="app_detailCourses")
     * Mètode per mostrar el detall d'un curs. Mostra el valor dels seus atributs.
     * @param Course $course objecte subject amb les dades de l'assignatura.
     */
    public function detail(Course $course): Response
    {
        return $this->render(
            'course/detail.html.twig',
            ['course' => $course]
        );
    }


    /**
     * @Route("/{id}/showsubjects", name="app_subjectByCourse")
     * Mètode que retorna les assignatures associades a un curs. 
     * @param Integer $id id del curs del qual es vol obtenir el llistat d'assignatures que pengen d'ell.
     */
    public function showSubjectsByCourse($id)
    {
        $subjects = $this->getDoctrine()
            ->getRepository(Subject::class)
            ->findBySubjectsByCourseId($id);
        return $this->render('course/showSubjectsByCourse.html.twig', [
            'subjects' => $subjects,
        ]);
    }

    /**
     * @Route("/{id}/showschedule", name="app_scheduleByCourse")
     * Mètode que retorna l'horari associat a un curs. 
     * @param Integer $id id del curs del qual es vol obtenir l'horari.
     */
    public function showScheduleByCourse($id)
    {
        $schedule = array();
        $scheduleRegisters = $this->getDoctrine()
            ->getRepository(Schedule::class)
            ->findByScheduleByCourseId($id);

        foreach ($scheduleRegisters as $register) {
            $schedule[$register->getDay()][$register->getHour()] = array(
                'teacher' => $register->getTeacher()->getName(),
                'subject' => $register->getSubject()->getName()
            );
        }

        return $this->render('course/showSchedule.html.twig', [
            'schedule' => $schedule,
        ]);
    }
}

www/teacher_planner/templates/course/add.html.twig
{% extends 'base.html.twig' %}
{% block title %}Afegir Curs{% endblock %}
{% block sectiontitle %}Afegir Curs{% endblock %}
{% block body %}

    <div class="row align-items-center justify-content-center gx-5">
        <div class="col-4">
            {{ form_start(form) }}
            <div class="my-custom-class-for-errors">
                {{ form_errors(form) }}
            </div>

            <div class="row">
                <div class="col">
                    {{ form_row(form.name, {'label': 'Nom'}) }}
                </div>
            </div>
            <div class="row">
                <div class="col" id="">
                    {{ form_row(form.cicle) }}
                </div>
            </div>
            {{ form_row(form.submit, { 'label': 'Afegir' }) }}
            {{ form_end(form) }}
        </div>
        <div class="col-6">
            <img src="{{ asset('images/takingnotes-amico.png') }}" alt="..." class="img-fluid">
        
        </div>
    </div>

{% endblock %}

www/teacher_planner/templates/course/allCourses.html.twig
{% extends 'base.html.twig' %}
{% block title %}Cursos{% endblock %}
{% block sectiontitle %}Cursos{% endblock %}
{% block body %}
    <div class="card card-bleed shadow-light-lg">
        <div class="card-header">
            <div class="row align-items-center">
                <div class="col">

                    <!-- Heading -->
                    <h4 class="mb-0">
                        Llista de Cursos
                    </h4>

                </div>
            </div>
        </div>
        <div class="card-body">
            <ul class="list-group list-group-flush">
            {% if allCourses | length > 0 %}
                {% for course in allCourses %}
                    <li class="list-group-item">
                        <div class="row align-items-center text-secondary">
                            <div class="col-auto">{{ course.id }}</div>
                            <div class="col">{{ course.name }} de {{ course.cicle == 'Primaria' ? 'Primària' : 'Secundària' }}</div>
                            {% if 'ROLE_ADMIN' in app.user.getRoles %}
                            <div class="col-auto">
                                <a class="btn btn-xs btn-primary text-decoration-none" href="{{ path('app_detailCourses', {id: course.id}) }}">
                                    Assignatures
                                </a>
                            </div>                            
                            {% endif %}
                        </div>
                    </li>
                {% endfor %}
            {% else %}
                <li class="list-group-item">
                    No n'hi ha
                </li>
            {% endif %}
            </ul>
        </div>
    </div>
{% endblock %}

www/teacher_planner/templates/course/detail.html.twig
{% extends 'base.html.twig' %}
{% block title %}Curs{% endblock %}
{% block sectiontitle %}{{ course.name }} de {{ course.cicle == 'Primaria' ? 'Primària' : 'Secundària' }}{% endblock %}
{% block body %}
    <div class="card card-bleed shadow-light-lg">
        <div class="card-header">
            <div class="row align-items-center">
                <div class="col">

                <!-- Heading -->
                <h4 class="mb-0">
                    Assignatures
                </h4>

                </div>
                <div class="col-auto">
                
                <!-- Button -->
                <a class="text-decoration-none text-white" href="{{ path('app_addSubject') }}/?selected_course_id={{ course.id }}">
                    <button class="btn btn-xs btn-primary">
                        Afegir
                    </button>
                </a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <ul class="list-group list-group-flush">
            {% if course.getSubjects | length > 0 %}
                {% for subject in course.getSubjects %}
                    <li class="list-group-item">
                        <div class="row align-items-center text-secondary">
                            <div class="col-auto">{{ subject.id }}</div>
                            <div class="col">{{ subject.name }} ({{ subject.hoursWeek }} hores lectives)</div>
                            <div class="col-auto">
                                <a href="../subjects/delete/{{ subject.id }}" class="text-decoration-none">
                                    <button class="col-auto btn btn-xs btn-danger">
                                    Esborrar
                                    </button>
                                </a>
                            </div>
                            <div class="col-auto">
                                <a href="{{ path('app_updateSubjects', {id: subject.id}) }}" class="text-decoration-none">
                                    <button class="col-auto btn btn-xs btn-primary">
                                    Editar
                                    </button>
                                </a>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            {% else %}
                <li class="list-group-item">
                    No n'hi ha
                </li>
            {% endif %}
            </ul>
        </div>
    </div>
{% endblock %}

www/teacher_planner/templates/course/showSchedule.html.twig
{% extends 'base.html.twig' %}
{% block title %}Horari{% endblock %}
{% block sectiontitle %}Horari{% endblock %}
{% set days = ['Dilluns', 'Dimarts', 'Dimecres', 'Dijous', 'Divendres'] %}
{% set timetable = ['08-09', '09-10', '10-11', '11-12', '12-13', '13-14'] %}
{% block body %}

<div class="container">
    {% for label, messages in app.flashes(['error']) %}
        {% for message in messages %}
            <div class="alert alert-warning alert-dismissible" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>        
        {% endfor %}
    {% endfor %}

{% if schedule|default %}
    {% if 'ROLE_ADMIN' in app.user.getRoles %}
    <a class="btn btn-lg btn-primary mb-5" href="{{path('app_generateSchedule')}}">
        Generar nou horari
    </a>
    {% endif %}
{% for key, cicle in schedule %}

<h3 class="pb-4">{{ key }}</h3>

    {% for key, course in cicle %}

    <h4 class="pb-4">{{ key }}</h4>

    <div class="table-responsive pb-4">
        <table class="table table-fixed table-bordered text-center">
            <thead>
                <tr class="bg-white">
                    <th class="text-uppercase">Hora
                    </th>
                    {% for day in days %}                    
                        <th style="width:18%" class="text-uppercase">{{day}}</th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody class="bg-white">
            {% for hour in timetable %}
                <tr>
                    <td style="width: 10%" class="align-middle">{{ hour }}</td>
                    {% for day in days %}
                        {% set emptycell = true %}
                        {% for entry in course %}
                            {% if entry.day == day and entry.hour == hour %}
                                {% set emptycell = false %}
                                <td class="p-3">
                                    <div class="bg-secondary p-1 rounded mb-1 text-white">{{ entry.subject.name }}</div>
                                    <div class="text-secondary">{{ entry.teacher.name }}</div>                                
                                </td>
                            {% endif %}
                        {% endfor %}
                        {% if emptycell == true%} 
                            <td class="p-3 bg-light">
                                <div class="p-1 rounded mb-1 text-white">&nbsp;</div>
                                <div class="text-secondary">&nbsp;</div>                              
                            </td>
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endfor %}    
            </tbody>
        </table>
    </div>
    {% endfor %}
{% endfor %}
{% else %}
    {% if 'ROLE_ADMIN' in app.user.getRoles %}
    <a class="btn btn-lg btn-primary mb-5" href="{{path('app_generateSchedule')}}">
        Generar horari
    </a>    
    {% endif %}
{% endif %}

</div>
{% endblock %}

www/teacher_planner/templates/course/showSubjectsByCourse.html.twig
{% extends 'base.html.twig' %}
{% block title %}Assignatures per Curs{% endblock %}
{% block body %}
    <table>
        {% for subject in subjects %}
            <tr>
                <td>{{ subject.name }}</td>
            </tr>
        {% else %}
            <tr>
                <td>No hay resultados.</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}